### ISSUE TITLE
安装指导

### ISSUE THREAD

**Issue by cloudwalkerfre** [justzx2011/openyoudao#53]
Fedora23, 先用mosquito仓库,显示同步失败,改用setup.py;安装完成后,点击图标,显示错误:

`Traceback (most recent call last):
  File "/usr/lib/openyoudao/openyoudao.py", line 9, in <module>
    import webshot
  File "/usr/lib/openyoudao/webshot.py", line 6, in <module>
    import gtk
ImportError: No `

求助,谢谢!

补充额外信息:

`$ python2 -c 'import sys; print("\n".join(sys.path))'

/usr/lib/python2.7/site-packages/pyPdf-1.13-py2.7.egg
/usr/lib/python2.7/site-packages/openyoudao-0.3-py2.7.egg
/usr/lib64/python27.zip
/usr/lib64/python2.7
/usr/lib64/python2.7/plat-linux2
/usr/lib64/python2.7/lib-tk
/usr/lib64/python2.7/lib-old
/usr/lib64/python2.7/lib-dynload
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/gtk-2.0
/usr/lib/python2.7/site-packages
`

**Comment by syrte** [comment]
没有gtk模块。 你需要通过系统安装 python-gtk 包及其依赖。
